server:
  port: 8081


# enable jodconverter lokal
jodconverter:
  local:
    enabled: true


# urutan prioritas properties: 1 application-test.yml, 2 application.properties, 3 application.yml
prop:
  test1: 1
  test2: 1

propTest_1:
  '{
    prop1: "property 1",
    prop2: "property 2"
  }'
propTest_2:
  prop1: property 1
  prop2: property 2
  nestedProp:
    prop1: nested property 1
    prop2: nested property 2
propTest_3:
  prop1: property 3.1
  prop2: property 3.2
propTest_4:
  prop1: property 4.1
  prop2: property 4.2



