server:
  port: 8999

spring:
  application:
    name: SpringTesting
  profiles:
    active: development
  # datasource example
  datasource:
    url: jdbc:mysql://localhost:3306/db_temp?useSSL=false&serverTimezone=Asia/Jakarta&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: root1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update


